'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,pick=a=>a[rand(0,a.length-1)],shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=rand(0,i);[a[i],a[j]]=[a[j],a[i]];}return a;},fmt=n=>Number(n.toFixed(2)).toLocaleString('it-IT');
const initial=()=>({version:1,current:0,max:0,done:[],seen:{},rewards:[],notes:0,variants:{},opened:{},retry:null,sound:true,finished:false,draws:{}});
let state=initial();try{const stored=JSON.parse(localStorage.getItem(CONFIG.storageKey));if(stored&&stored.version===1&&Number.isInteger(stored.current)&&stored.current>=0&&stored.current<SCENES.length)state={...state,...stored};}catch(e){}
if(state.variants.sequence&&!state.variants.sequence.kind)delete state.variants.sequence;
let viewer,spots=[],lastFocus=null,activeSceneToken=0,audioCtx,toastTimer,modalLocked=false;const scene=()=>SCENES[state.current];
function save(){try{localStorage.setItem(CONFIG.storageKey,JSON.stringify(state));}catch(e){toast('I progressi resteranno disponibili solo finché questa pagina rimane aperta.');}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4000);}
function close(){if(modalLocked)return;leaveIntroVideo();for(const v of $('#modal').querySelectorAll('video,audio'))v.pause();$('#modal').hidden=true;$('#dialogContent').innerHTML='';$('#panorama').inert=false;lastFocus?.focus?.();}
function modal(title,body,actions=[],eyebrow='MATE E IL VIAGGIO A CROTONE'){
 leaveIntroVideo();for(const v of $('#modal').querySelectorAll('video,audio'))v.pause();modalLocked=false;$('#closeModal').hidden=false;lastFocus=document.activeElement;$('#dialogContent').innerHTML=`<div class="eyebrow">${eyebrow}</div><h2 id="dialogTitle">${title}</h2>${body}<div class="actions" id="modalActions"></div>`;for(const [label,fn,cls=''] of actions){const b=document.createElement('button');b.textContent=label;b.className=cls;b.onclick=fn;$('#modalActions').appendChild(b);}$('#modal').hidden=false;$('#panorama').inert=true;$('#closeModal').focus();$('.card').scrollTop=0;
}
$('#closeModal').onclick=close;
document.addEventListener('keydown',e=>{if(!$('#modal').hidden){if(e.key==='Escape'){close();return;}if(e.key==='Tab'){const focus=[...$('#modal').querySelectorAll('button,input,video,audio,a')].filter(x=>!x.disabled&&x.offsetParent!==null);const first=focus[0],last=focus.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(/INPUT|TEXTAREA/.test(document.activeElement.tagName)||!viewer)return;if(e.key==='ArrowLeft')viewer.lon-=8;if(e.key==='ArrowRight')viewer.lon+=8;if(e.key==='ArrowUp')viewer.lat=Math.min(60,viewer.lat+6);if(e.key==='ArrowDown')viewer.lat=Math.max(-60,viewer.lat-6);});
function star(){const p=Array.from({length:5},(_,i)=>{const a=(-90+72*i)*Math.PI/180;return [110+83*Math.cos(a),110+83*Math.sin(a)];});const outer=p.map(x=>x.join(',')).join(' '),inner=[0,2,4,1,3,0].map(i=>p[i].join(',')).join(' ');return `<svg viewBox="0 0 220 220" aria-label="Pentagono regolare con stella a cinque punte inscritta" role="img"><defs><radialGradient id="goldMedal"><stop stop-color="#ffe7a1"/><stop offset=".72" stop-color="#b47821"/><stop offset="1" stop-color="#553713"/></radialGradient></defs><circle cx="110" cy="110" r="105" fill="url(#goldMedal)" stroke="#ffe5a1" stroke-width="3"/><circle cx="110" cy="110" r="96" fill="#102c35" stroke="#dcb669" stroke-width="2"/><polygon points="${outer}" fill="#e2b95d19" stroke="#ffe39a" stroke-width="4"/><polyline points="${inner}" fill="none" stroke="#f6cc70" stroke-width="4" stroke-linejoin="round"/>${p.map(([x,y])=>`<circle cx="${x}" cy="${y}" r="5" fill="#fff0bd"/>`).join('')}</svg>`;}
function staff(){return '<svg viewBox="0 0 210 120" role="img" aria-label="Pentagramma musicale"><g stroke="#f5d48d" stroke-width="2"><path d="M10 30H200M10 45H200M10 60H200M10 75H200M10 90H200"/></g><g fill="#f5d48d"><ellipse cx="55" cy="75" rx="10" ry="7"/><ellipse cx="105" cy="60" rx="10" ry="7"/><ellipse cx="150" cy="45" rx="10" ry="7"/></g><g stroke="#f5d48d" stroke-width="3"><path d="M64 75V22M114 60V7M159 45V0"/></g></svg>';}
function triangleSVG(a='a',b='b',c='c',squares=false){return `<svg viewBox="0 0 340 230" role="img" aria-label="Triangolo rettangolo: cateti ${esc(a)} e ${esc(b)}, ipotenusa ${esc(c)}"><path d="M65 25V185H275Z" fill="#76c9c322" stroke="#e7c47f" stroke-width="4"/><path d="M65 165H85V185" fill="none" stroke="#e7c47f" stroke-width="2"/><g fill="currentColor" font-size="21" font-family="Georgia"><text x="20" y="112">${esc(a)}</text><text x="156" y="215">${esc(b)}</text><text x="180" y="92">${esc(c)}</text></g>${squares?'<text x="114" y="148" fill="currentColor" font-size="20">a² + b² = c²</text>':''}</svg>`;}
function ropeSVG(){const pts=[[60,150],[60,110],[60,70],[60,30],[92,54],[124,78],[156,102],[188,126],[220,150],[180,150],[140,150],[100,150]];return `<svg viewBox="0 0 285 205" role="img" aria-label="Corda chiusa con 12 intervalli uguali: lati di 3, 4 e 5 unità"><path d="M60 150V30L220 150Z" fill="#73c4be22" stroke="#e1b965" stroke-width="5"/><path d="M60 134H76V150" fill="none" stroke="#fff" stroke-width="2"/>${pts.map(([x,y])=>`<circle cx="${x}" cy="${y}" r="5" fill="#fff1c1" stroke="#835824"/>`).join('')}<g fill="white" font-size="22"><text x="27" y="95">3</text><text x="130" y="182">4</text><text x="161" y="75">5</text></g></svg>`;}
function squaresSVG(){return '<svg viewBox="0 -65 360 365" role="img" aria-label="Quadrati sui lati: 9 più 16 uguale 25"><g stroke="#fff2c8" stroke-width="2"><path d="M120 160V70L240 160Z" fill="#ffffff22"/><path d="M120 70H30V160H120Z" fill="#70b9c7aa"/><path d="M120 160H240V280H120Z" fill="#e3ba67aa"/><path d="M120 70 240 160 330 40 210 -50Z" fill="#b99ada99"/></g><g fill="white" font-size="22"><text x="61" y="123">9</text><text x="165" y="229">16</text><text x="211" y="63">25</text></g></svg>';}
function beep(ratio=1,duration=.55,start=0){if(!state.sound)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+start;o.type='sine';o.frequency.value=261.6256*ratio;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.16,t+.03);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+duration+.02);}catch(e){toast('Il browser non rende disponibile l’audio. Puoi proseguire leggendo le schede.');}}
function interval(r){beep(1,.65);beep(r,.65,.8);}
function musicalScale(){[1,9/8,81/64,4/3,3/2,27/16,243/128].forEach((r,i)=>beep(r,.48,i*.52));}
function celebrate(music=false){if(!matchMedia('(prefers-reduced-motion: reduce)').matches){$('#celebration').innerHTML=Array.from({length:20},(_,i)=>`<span class="spark" style="left:${rand(0,100)}%;animation-delay:${i*.025}s">✦</span>`).join('');setTimeout(()=>$('#celebration').innerHTML='',3000);}if(music)musicalScale();else{beep(1,.3);beep(1.25,.3,.15);beep(1.5,.5,.3);}}
function draw(key,values){state.draws=state.draws||{};let bag=state.draws[key]||[];if(!bag.length)bag=shuffle(values);const value=bag.pop();state.draws[key]=bag;return value;}
function arrivalRead(id){if(state.current!==0)return;state.seen.arrival=state.seen.arrival||[];if(!state.seen.arrival.includes(id))state.seen.arrival.push(id);if(['harbor','welcome'].every(x=>state.seen.arrival.includes(x)))markDone();save();buildSpots();refresh();}
function finishWelcome(){arrivalRead('welcome');close();}
function resourceSet(){return scene().explore==='rules'?RULES:scene().explore==='music'?MUSIC:GEOMETRY;}
function ready(){if(state.current===0)return ['harbor','welcome'].every(x=>(state.seen.arrival||[]).includes(x));return state.done.includes(state.current)&&state.retry!==state.current;}
function refresh(){const s=scene();$('#chapter').textContent=s.chapter?`CAPITOLO ${s.chapter} · ${['','IL SEGRETO DEI PITAGORICI','L’ARMONIA DEI NUMERI','IL SEGRETO DELLA DIAGONALE'][s.chapter]}`:'MATE E IL VIAGGIO A CROTONE';$('#sceneTitle').textContent=s.title;$('#missionText').textContent=s.mission;$('#bagCount').textContent=state.rewards.length;$('#continue').hidden=!ready()||state.current===14;$('#continue').textContent=state.current===0?'Inizia la missione →':[5,7].includes(state.current)?'Apri il prossimo capitolo →':'Prosegui →';if(state.current===0){$('#sceneProgress').textContent=`Scoperte ${(state.seen.arrival||[]).length} / 2`;}else if(s.explore){$('#sceneProgress').textContent=`Scoperte ${(state.seen[s.id]||[]).length} / ${resourceSet().length}`;}else if(s.task==='notes')$('#sceneProgress').textContent=`Note ritrovate ${state.notes} / 7`;else $('#sceneProgress').textContent=state.current===14?'Missione compiuta':ready()?'Tappa superata ✓':`Tappa ${state.current+1} di 15`;$('#sound').setAttribute('aria-pressed',String(state.sound));$('#sound').textContent=state.sound?'♪':'♩';$('#sound').setAttribute('aria-label',state.sound?'Disattiva i suoni':'Attiva i suoni');}
function addSpot(spec){const b=document.createElement('button');b.className='spot'+(spec.prop?' prop':'')+(spec.className?' '+spec.className:'');b.setAttribute('aria-label',spec.label||'Oggetto esplorabile');b.dataset.id=spec.id;const seen=(state.seen[scene().id]||[]).includes(spec.id);if(seen)b.classList.add('visited');b.innerHTML=spec.html||`<span class="marker">${seen?'✓':'✧'}</span><span class="spot-label">${esc(spec.label)}</span>`;if(spec.decorative){b.tabIndex=-1;b.setAttribute('aria-hidden','true');}b.onclick=()=>spec.fn?spec.fn():activate(spec);let down;b.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});b.addEventListener('click',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>12){e.preventDefault();e.stopImmediatePropagation();}},true);$('#hotspots').appendChild(b);spots.push({b,spec});}
function buildSpots(){spots=[];$('#hotspots').innerHTML='';const s=scene();if(s.explore){resourceSet().forEach((r,i)=>addSpot({id:String(i),u:r[2],v:r[3],w:90,h:85,label:r[0],fn:()=>resource(i)}));}else(s.spots||[]).forEach(addSpot);if(state.opened[s.id]&&['rope','ladder','square'].includes(s.task))props();}
function project(){if(!viewer)return;for(const {b,spec}of spots){const p=viewer.project(spec.u,spec.v);if(!p){b.style.display='none';continue;}b.style.display='block';b.style.left=p.x+'px';b.style.top=p.y+'px';const scale=Math.min(1.6,72/viewer.fov)*(innerWidth<650?.8:1);b.style.width=Math.max(44,(spec.w||90)*scale)+'px';b.style.height=Math.max(44,(spec.h||80)*scale)+'px';}}
async function go(i){if(i<0||i>=SCENES.length||i>state.max)return;close();state.current=i;save();refresh();buildSpots();document.body.classList.remove('show-spots');$('#reveal').setAttribute('aria-pressed','false');$('#reveal').textContent='✧ Mostra curiosità';$('#loading').hidden=false;const t=++activeSceneToken;try{if(!viewer)throw new Error('WebGL');viewer.maxFov=110;await viewer.setImage(scene().image,scene().start||.5,.52);if(t!==activeSceneToken)return;$('#loading').hidden=true;const next=SCENES[i+1];if(next){const img=new Image();img.src=next.image;}}catch(e){if(t!==activeSceneToken)return;$('#loading').hidden=true;modal('Il panorama non si è caricato','<p>Controlla che tutti i file del pacchetto siano nella stessa cartella e che il browser supporti WebGL.</p><p class="small">Se hai aperto il file direttamente dal computer, prova la versione pubblicata su un sito oppure avvia il server locale descritto nella guida.</p>',[['Riprova',()=>go(i),'primary']]);}}
function next(){if(!ready())return;state.max=Math.max(state.max,Math.min(14,state.current+1));save();go(Math.min(14,state.current+1));}
function markDone(){if(!state.done.includes(state.current))state.done.push(state.current);if(state.retry===state.current)state.retry=null;state.max=Math.max(state.max,Math.min(14,state.current+1));save();refresh();}
function success(message,reward=scene().reward){markDone();const isNew=reward&&!state.rewards.includes(reward);if(isNew)state.rewards.push(reward);save();refresh();celebrate(reward==='Pentagramma musicale');modal('Hai trovato la strada!',`<p>${message}</p>${reward?`<div class="reward">${reward==='Stella pitagorica'?star():reward==='Pentagramma musicale'?staff():esc(reward)}</div><p class="small">${isNew?'La ricompensa è stata aggiunta al tuo viaggio.':'Questa ricompensa è già nel tuo viaggio.'}</p>`:''}`,[['Prosegui →',next,'primary'],['Esplora ancora',close]],'PROVA SUPERATA');}
function wrong(explanation){if(scene().task==='sequence'){beep(.7,.4);modal('Scopri la regola',`<p>${explanation}</p><p>Ora prova una nuova successione.</p>`,[['Nuova prova',()=>{delete state.variants.sequence;save();task();},'primary']]);return;}const failed=state.current,back=scene().back??Math.max(0,failed-1);beep(.7,.4);modal('Un passo indietro per capire',`<p>${explanation}</p><p class="small">Tornerai a «${SCENES[back].title}». Gli indizi e le note già conquistati restano con te.</p>`,[['Torna alla tappa precedente',()=>{modalLocked=false;delete state.variants[SCENES[failed].id];if(failed===7)delete state.variants['music'+state.notes];delete state.opened[SCENES[failed].id];delete state.variants[SCENES[back].id];delete state.opened[SCENES[back].id];if(back===12)delete state.opened.squareSign;state.retry=back;if(SCENES[back].explore)state.seen[SCENES[back].id]=[];save();go(back);},'primary']]);modalLocked=true;$('#closeModal').hidden=true;$('#modalActions button').focus();}
function activate(s){if(s.action==='intro')intro();else if(s.action==='task')task();else if(s.action==='sign')sign();else if(s.action==='finale')finale();else modal(s.label,`<p>${s.text}</p>`,[['Continua a esplorare',()=>{if(state.current===0)arrivalRead(s.id);close();},'primary']],'UNA SCOPERTA');}
let introOwnFullscreen=false;
function leaveIntroVideo(){
 $('#modal').classList.remove('video-intro');
 if(introOwnFullscreen){introOwnFullscreen=false;if(document.fullscreenElement&&document.exitFullscreen)document.exitFullscreen().catch(()=>{});}
}
function intro(){
 if(!CONFIG.introVideo){missionText();return;}
 modal('Il benvenuto di Pitagora',`<div class="intro-stage"><video id="introFilm" controls playsinline preload="auto" poster="01-crotone.webp" src="${esc(CONFIG.introVideo)}"></video><button id="introPlay" class="intro-play primary">▶ Avvia il video con audio</button><p id="introVideoStatus" role="status"></p></div>`,[['Leggi la missione',missionText],['Torna all’esplorazione',finishWelcome,'primary']]);
 $('#modal').classList.add('video-intro');
 const film=$('#introFilm'),play=$('#introPlay'),status=$('#introVideoStatus');
 const start=()=>{const result=film.play();if(result&&result.catch)result.catch(()=>{play.hidden=false;status.textContent='Tocca il pulsante per avviare il video.';});};
 play.onclick=()=>{if(!document.fullscreenElement&&document.documentElement.requestFullscreen){document.documentElement.requestFullscreen().then(()=>{if($('#modal').classList.contains('video-intro'))introOwnFullscreen=true;else document.exitFullscreen?.().catch(()=>{});}).catch(()=>{});}start();};
 film.onplaying=()=>{play.hidden=true;status.textContent='';};
 film.onpause=()=>{if(!film.ended){play.textContent='▶ Riprendi il video';play.hidden=false;}};
 film.onended=()=>{arrivalRead('welcome');play.textContent='↻ Riguarda il video';play.hidden=false;status.textContent='Ora puoi iniziare la missione.';};
 film.onerror=()=>{play.hidden=true;status.textContent='Il video non si è caricato. Puoi scegliere “Leggi la missione” e proseguire.';};
 start();
}
function missionText(){const body=`<p>«Benvenuta a Crotone, Mate! Il mio discepolo <b>Ippaso è scomparso insieme a un segreto</b>. Qualcuno lo ha rinchiuso in un’ampolla destinata a una nave in partenza.</p><p>Per ritrovarlo dovrai entrare nella nostra comunità, ascoltare l’armonia dei numeri e scoprire la forza dei triangoli. Il viaggio comincia da qui!»</p><p class="small">Un’avventura di fantasia intrecciata alla matematica e alle tradizioni su Pitagora. Nessun conto alla rovescia: prenditi il tempo per esplorare.</p>`;modal('Mate e il Viaggio a Crotone',body,[['Ho ascoltato la missione',finishWelcome,'primary'],...(CONFIG.introVideo?[['Guarda il video',intro]]:[])],'UN DISCEPOLO DA RITROVARE · UN SEGRETO DA LIBERARE');}
function resource(i){const r=resourceSet()[i],type=scene().explore;let extra='';if(type==='geometry'&&i===0)extra=`<div class="diagram-wrap">${ropeSVG()}</div>`;if(type==='geometry'&&i>=3)extra=`<div class="diagram-wrap">${triangleSVG('a','b','c',i===4)}</div>${i===4?'<div class="diagram-wrap">'+squaresSVG()+'</div><p class="math">9 + 16 = 25<br>c = √(a² + b²)</p>':''}`;const actions=[];if(type==='music'&&['octave','fifth','fourth'].includes(r[4]))actions.push(['Ascolta i due suoni',()=>interval({octave:2,fifth:1.5,fourth:4/3}[r[4]]),'primary']);if(type==='music'&&r[4]==='mono')actions.push(['Ascolta: corda intera e metà',()=>interval(2),'primary']);actions.push(['Ho esplorato questa risorsa',()=>{const id=scene().id;state.seen[id]=state.seen[id]||[];if(!state.seen[id].includes(String(i)))state.seen[id].push(String(i));if(state.seen[id].length===resourceSet().length)markDone();save();close();buildSpots();refresh();if(ready())toast('Hai esplorato tutte le risorse. Ora puoi proseguire.');}]);modal(r[0],`<p>${r[1]}</p>${extra}`,actions,type==='rules'?'TRADIZIONI DELLA COMUNITÀ':type==='music'?'IL LABORATORIO DEI SUONI':'IL LABORATORIO DEI TRIANGOLI');}
function variant(){const id=scene().id;if(state.variants[id])return state.variants[id];let v={};switch(scene().task){case'pebbles':{const n=draw('pebbleRows',[3,4,5,6]);v={n,answer:n*(n+1)/2};break;}case'pairs':{const n=2*rand(5,14)+draw('parity',[0,1]);v={n,answer:n%2===0?'Pari':'Dispari'};break;}case'sequence':{const kind=draw('sequenceKind',['add','multiply','growing','alternate']),start=rand(1,5),step=rand(2,5);let seq=[start],why='';for(let i=0;i<4;i++)seq.push(kind==='multiply'?seq.at(-1)*step:seq.at(-1)+(kind==='growing'?step+i:kind==='alternate'?(i%2?step+2:step):step));if(kind==='add')why=`Ogni passo aggiunge ${step}.`;if(kind==='multiply')why=`Ogni termine viene moltiplicato per ${step}.`;if(kind==='growing')why=`Si aggiungono ${step}, ${step+1}, ${step+2}, poi ${step+3}: gli incrementi crescono di 1.`;if(kind==='alternate')why=`Si aggiungono alternativamente ${step} e ${step+2}.`;v={kind,step,seq:seq.slice(0,4),answer:seq[4],why};break;}case'rope':{const [a,b,c]=pick(TRIPLES);const answer=a+b+c;v={a,b,c,answer,choices:shuffle([answer,answer+2,answer-2])};break;}case'triangle':v=pick([{q:'Qual è il lato opposto all’angolo retto?',choices:['L’ipotenusa','Un cateto','La base in ogni triangolo'],answer:'L’ipotenusa',why:'L’ipotenusa è sempre opposta all’angolo retto.'},{q:'Come si chiamano i due lati che formano l’angolo retto?',choices:['Cateti','Ipotenuse','Diagonali'],answer:'Cateti',why:'I due lati che si incontrano nell’angolo di 90° sono i cateti.'},{q:'Quanto misura l’angolo retto?',choices:['90°','60°','180°'],answer:'90°',why:'Un angolo retto misura 90°.'},{q:'Qual è sempre il lato più lungo di un triangolo rettangolo?',choices:['L’ipotenusa','Il cateto verticale','Dipende da come lo ruoti'],answer:'L’ipotenusa',why:'L’ipotenusa resta il lato più lungo anche ruotando il triangolo.'}]);v={...v,choices:shuffle(v.choices)};break;case'hypotenuse':{const [a,b,c]=pick(TRIPLES);v={a,b,c,answer:c};break;}case'square':{const side=pick([10,12,15,20,25,30,40,50]);v={side,diagonal:side*1.41,answer:Math.round(side*.59*100)/100};break;}case'ladder':{const [distance,height,c]=pick([[3,4,5],[5,12,13],[8,15,17],[6,8,10],[9,12,15]]);v={distance,height,c,answer:distance,choices:shuffle([distance,distance+1,distance+3,Math.max(1,distance-2)])};break;}}
state.variants[id]=v;save();return v;}
function numberForm(title,body,answer,correct,explanation,tolerance=.001){modal(title,`${body}<form id="answerForm"><label for="answer">La tua risposta</label><input id="answer" inputmode="decimal" autocomplete="off" placeholder="Scrivi il numero" required><button class="primary" type="submit">Verifica la risposta</button><p class="small">Puoi usare la virgola o il punto per i decimali.</p></form>`);$('#answerForm').onsubmit=e=>{e.preventDefault();const raw=$('#answer').value.trim().replace(',','.');if(!/^\d+(\.\d+)?$/.test(raw)){toast('Inserisci solo un numero positivo, senza unità di misura.');return;}const n=Number(raw);Math.abs(n-answer)<=tolerance?correct():wrong(explanation);};$('#answer').focus();}
function choiceForm(title,body,choices,answer,correct,explanation){modal(title,body+'<div class="choices" id="choiceList"></div>');for(const c of choices){const b=document.createElement('button');b.textContent=c;b.onclick=()=>c===answer?correct():wrong(explanation);$('#choiceList').appendChild(b);}}
function task(){const s=scene(),v=variant();if(ready()&&s.task!=='notes'){modal('Tappa già superata','<p>Hai già conquistato questa tappa. Puoi continuare il viaggio o esplorare ancora.</p>',[['Prosegui',next,'primary'],['Esplora ancora',close]]);return;}state.opened[s.id]=true;save();
switch(s.task){case'pebbles':{const dots=Array.from({length:v.n},(_,i)=>`<div style="text-align:center;letter-spacing:9px;color:#f4d9a6">${'●'.repeat(i+1)}</div>`).join('');numberForm('Un numero prende forma',`<p>Disponi i sassolini in ${v.n} righe: la prima ne contiene 1, la seconda 2, e così via fino a ${v.n}. Quanti sassolini servono in tutto?</p><div class="math">${dots}</div>`,v.answer,()=>success(`Hai contato ${v.answer} sassolini e scoperto un numero triangolare.`),`Somma i sassolini delle righe: ${Array.from({length:v.n},(_,i)=>i+1).join(' + ')} = ${v.answer}.`);break;}
case'pairs':choiceForm('Tutti in coppia?',`<p>Nel cestino ci sono <b>${v.n} pedine</b>. Il numero è pari oppure dispari?</p>`,['Pari','Dispari'],v.answer,()=>success(`${v.n} è ${v.answer.toLowerCase()}: ${v.n%2?'rimane una pedina senza compagna':'tutte le pedine formano coppie'}.`),`${v.n} è ${v.answer.toLowerCase()}. Un numero pari si divide in coppie senza avanzi; uno dispari lascia un oggetto solo.`);break;
case'sequence':numberForm('La regola nascosta',`<p>Osserva la successione. Quale numero viene dopo?</p><div class="math">${v.seq.join(' · ')} · ?</div>`,v.answer,()=>success(`La regola prevista è questa: ${v.why} Il prossimo numero è ${v.answer}.`),`La regola prevista in questa prova è: ${v.why} Il termine successivo è ${v.answer}.`);break;
case'motto':motto();break;
case'notes':musicQuiz();break;
case'rope':modal('Quale corda chiusa?',`<p>Devi costruire un triangolo rettangolo con cateti di <b>${v.a}</b> e <b>${v.b} unità</b>. La corda chiusa deve formare <b>l’intero perimetro</b>, senza avanzi.</p><p>Scegli sul terreno la corda della lunghezza totale corretta.</p><div class="diagram-wrap">${triangleSVG(v.a,v.b,'?')}</div>`,[['Scegli una corda nella scena',()=>{close();buildSpots();viewer.look(.5,.70);},'primary']]);break;
case'triangle':choiceForm('Riconosci il triangolo',`<p>${v.q}</p><div class="diagram-wrap">${triangleSVG()}</div>`,v.choices,v.answer,()=>success(v.why),v.why);break;
case'hypotenuse':numberForm('Quanto deve essere lungo il passaggio?',`<p>I cateti del triangolo rettangolo misurano <b>${v.a} m</b> e <b>${v.b} m</b>. Quanto misura l’ipotenusa che collega i due estremi?</p><div class="diagram-wrap">${triangleSVG(v.a+' m',v.b+' m','?')}</div>`,v.c,()=>success(`√(${v.a}² + ${v.b}²) = √${v.c*v.c} = ${v.c} m. Il passaggio è pronto.`),`Devi sommare i quadrati dei cateti e poi estrarre la radice: √(${v.a*v.a} + ${v.b*v.b}) = ${v.c} m.`);break;
case'square':if(!state.opened.squareSign){modal('Prima leggi il cartello','<p>Il cartello vicino alla piazza indica la lunghezza del lato. Trovalo e toccalo per leggerlo ingrandito.</p>',[['Torna alla piazza',close,'primary']]);}else squareTask();break;
case'ladder':modal('Raggiungi l’ampolla',`<p>La mensola con l’ampolla si trova a <b>${v.height} m</b> dal terreno. La scala è lunga <b>${v.c} m</b>. Il terreno è orizzontale e il muro verticale.</p><p>A quale distanza dal muro devi mettere la base della scala affinché la sua estremità raggiunga esattamente la mensola?</p>`,[['Scegli un solco nel terreno',()=>{close();buildSpots();viewer.look(.5,.65);},'primary']]);break;}}
function props(){const s=scene(),v=variant();if(s.task==='rope'){v.choices.forEach((n,i)=>addSpot({id:'rope'+i,u:[.33,.505,.68][i],v:.772,w:105,h:50,label:`Corda lunga ${n} unità`,prop:true,html:`${n} unità`,fn:()=>n===v.answer?success(`L’ipotenusa è ${v.c}. Il perimetro è ${v.a} + ${v.b} + ${v.c} = ${v.answer} unità.`):wrong(`Il teorema dà un’ipotenusa di ${v.c} unità. La corda deve essere lunga ${v.answer} unità, cioè la somma dei tre lati.`)}));}if(s.task==='ladder'){v.choices.forEach((n,i)=>addSpot({id:'groove'+i,u:.41+i*.06,v:.72,w:92,h:50,label:`Solco a ${n} metri dal muro`,prop:true,html:`${n} m`,fn:()=>n===v.answer?ladderWin():wrong(`Usa la relazione d = √(scala² − altezza²). La distanza corretta è √(${v.c}² − ${v.height}²) = ${v.distance} m. Sottrai i quadrati: la scala è l’ipotenusa.`)}));}if(s.task==='square'&&state.opened.squareSign)addSpot({id:'measure',u:.375,v:.648,w:105,h:47,label:'Rileggi la misura del lato',prop:true,html:`Lato ${v.side} m`,fn:sign});}
function sign(){const v=variant();state.opened.squareSign=true;state.opened.square=true;save();buildSpots();modal('Il cartello della piazza',`<div class="reward">${v.side} m</div><p>Questa è la lunghezza di <b>ciascun lato</b> della piazza quadrata.</p><p>Devi andare da un vertice al vertice opposto. Puoi attraversare la diagonale oppure percorrere due lati consecutivi.</p><p class="math">Usa √2 ≈ 1,41</p>`,[['Ho letto il cartello',close,'primary']]);}
function squareTask(){const v=variant();modal('Quale strada scegli?',`<p>Il lato della piazza misura <b>${v.side} m</b>. Confronta i percorsi fra gli stessi vertici opposti usando <b>√2 ≈ 1,41</b>.</p><div class="diagram-wrap"><svg viewBox="0 0 300 210" role="img" aria-label="Piazza quadrata: percorso lungo due lati e diagonale"><path d="M65 175V25H215V175Z" fill="#ffffff10" stroke="#ffe0a2" stroke-width="3"/><path d="M65 175V25H215" fill="none" stroke="#83d7cf" stroke-width="7"/><path d="M65 175 215 25" stroke="#f6cb77" stroke-width="5"/><g fill="white" font-size="17"><text x="40" y="199">Partenza</text><text x="209" y="19">Arrivo</text><text x="15" y="105">${v.side} m</text></g></svg></div><form id="squareForm"><fieldset style="border:0;padding:0"><legend>Quale percorso è più breve?</legend><label><input type="radio" name="route" value="diagonal" required style="width:auto"> La diagonale</label><br><label><input type="radio" name="route" value="sides" required style="width:auto"> Due lati consecutivi</label></fieldset><label for="saving">Quanti metri risparmi?</label><input id="saving" inputmode="decimal" placeholder="Risparmio in metri" required><button class="primary">Verifica entrambe le risposte</button></form>`);$('#squareForm').onsubmit=e=>{e.preventDefault();const route=$('input[name=route]:checked')?.value,raw=$('#saving').value.trim().replace(',','.');if(!/^\d+(\.\d+)?$/.test(raw)){toast('Scrivi il risparmio come numero, senza unità.');return;}route==='diagonal'&&Math.abs(Number(raw)-v.answer)<.011?success(`La diagonale misura circa ${fmt(v.diagonal)} m; due lati misurano ${v.side*2} m. Risparmi circa ${fmt(v.answer)} m.`):wrong(`La diagonale è più breve: ${v.side} × 1,41 = ${fmt(v.diagonal)} m. Il risparmio è ${v.side*2} − ${fmt(v.diagonal)} = ${fmt(v.answer)} m.`);};}
function ladderWin(){const v=variant(),sceneToken=activeSceneToken;close();document.querySelectorAll?.('#hotspots .prop').forEach(b=>b.disabled=true);addSpot({id:'placedLadder',u:.50,v:.54,w:150,h:310,prop:true,className:'ladder',decorative:true,html:'<svg viewBox="0 0 100 300"><g stroke="#e8b96c" stroke-width="7"><path d="M22 290 45 12M48 290 71 12"/>'+Array.from({length:11},(_,i)=>`<path d="M${24+i*2} ${275-i*23}h26"/>`).join('')+'</g></svg>'});setTimeout(()=>{if(state.current!==13||sceneToken!==activeSceneToken)return;success(`La scala è al posto giusto: √(${v.c}² − ${v.height}²) = ${v.distance} m. Mate raggiunge l’ampolla e libera Ippaso! Hai completato l’indizio RADICE DI DUE.`,'DUE');},1300);}
function motto(){const needed=['TUTTO','È','NUMERO'];if(!needed.every(x=>state.rewards.includes(x))){toast('Ti servono prima tutti e tre i frammenti.');return;}let words=[];modal('Le parole che aprono la porta','<p>Tocca le tre parole nell’ordine giusto.</p><div class="slots" id="slots"></div><div class="tiles" id="tiles"></div>',[['Ricomincia la frase',()=>{words=[];draw();}],['Apri la porta',()=>words.join(' ')==='TUTTO È NUMERO'?success('La porta si apre. Il pentagono stellato ti riconosce come compagna di viaggio: ora puoi cercare l’armonia dei numeri.','Stella pitagorica'):wrong('Il motto del nostro viaggio è «Tutto è numero». Cerca l’ordine delle tre parole.'),'primary']]);const order=shuffle(needed);function draw(){$('#slots').innerHTML=words.map(x=>`<span>${x}</span>`).join('')+Array.from({length:3-words.length},()=>'<span class="slot-empty"></span>').join('');$('#tiles').innerHTML='';for(const word of order){const b=document.createElement('button');b.textContent=word;b.disabled=words.includes(word);b.onclick=()=>{words.push(word);draw();};$('#tiles').appendChild(b);}}draw();}
function musicQuestion(n){const key='music'+n;if(state.variants[key])return state.variants[key];const L=draw('musicLength'+n,[24,36,48,60,72]),F=draw('musicFrequency'+n,[180,240,300,360]);const bank=[
{q:`Una corda ha una parte vibrante lunga ${L} cm. Quale lunghezza serve per ottenere un’ottava sopra?`,answer:L/2,why:`Per salire di un’ottava si dimezza la lunghezza: ${L} ÷ 2 = ${L/2} cm.`,number:true},
{q:`Una corda vibra a ${F} Hz. Quale frequenza avrà il suono un’ottava sopra?`,answer:F*2,why:`Nell’ottava superiore la frequenza raddoppia: ${F} × 2 = ${F*2} Hz.`,number:true},
{q:`Due suoni hanno frequenze ${F} Hz e ${F*2} Hz. Quale intervallo formano?`,choices:['Ottava','Quinta','Quarta'],answer:'Ottava',why:`${F*2} : ${F} = 2 : 1: è un’ottava.`},
{q:`Due suoni hanno frequenze ${F} Hz e ${F*1.5} Hz. Quale intervallo formano?`,choices:['Ottava','Quinta','Quarta'],answer:'Quinta',why:`${F*1.5} : ${F} = 3 : 2: è una quinta.`},
{q:`La parte vibrante di una corda misura ${L} cm. Quale lunghezza serve per ottenere una quinta sopra?`,answer:L*2/3,why:`Per una quinta superiore la lunghezza diventa 2/3: ${L} ÷ 3 × 2 = ${L*2/3} cm.`,number:true},
{q:`La parte vibrante di una corda passa da ${L} cm a ${L*3/4} cm. Quale intervallo produce?`,choices:['Ottava','Quinta','Quarta'],answer:'Quarta',why:`${L*3/4} : ${L} = 3 : 4 per le lunghezze; le frequenze sono nel rapporto inverso 4 : 3: è una quarta.`},
{q:`Un suono ha frequenza ${F} Hz. Quale frequenza deve avere il suono una quarta sopra?`,answer:F*4/3,why:`Nella quarta superiore la frequenza diventa 4/3: ${F} ÷ 3 × 4 = ${F*4/3} Hz.`,number:true}
];state.variants[key]=bank[n];save();return bank[n];}
function musicQuiz(){if(state.notes>=7){success('Le sette note sono di nuovo insieme. Il pentagramma musicale è il tuo secondo dono.','Pentagramma musicale');return;}const n=state.notes,q=musicQuestion(n),names=['DO','RE','MI','FA','SOL','LA','SI'];const top=`<div class="notes">${names.map((x,i)=>`<span class="note ${i<n?'got':''}">${x}</span>`).join('')}</div><p>${q.q}</p>`;const win=()=>{state.notes++;save();refresh();if(state.notes<7)beep([1,9/8,81/64,4/3,3/2,27/16,243/128][n]);if(state.notes===7){success('Hai ricomposto DO, RE, MI, FA, SOL, LA, SI. Ricevi il pentagramma musicale: uno strumento moderno che Mate porta nel suo viaggio.','Pentagramma musicale');}else modal('Una nota ritrovata',`<div class="reward">${names[n]}</div><p>${q.why}</p>`,[['Prossima nota',musicQuiz,'primary'],['Esplora ancora',close]],`${state.notes} NOTE SU 7`);};if(q.number)numberForm('Le sette note · '+(n+1)+'/7',top,q.answer,win,q.why);else choiceForm('Le sette note · '+(n+1)+'/7',top,shuffle(q.choices),q.answer,win,q.why);}
function video(url,title,back){modal(title,`<video controls playsinline preload="metadata" src="${esc(url)}"></video><p class="small" id="videoStatus"></p>`,[['Torna al racconto',back]]);$('video').onerror=()=>$('#videoStatus').textContent='Il video non è disponibile. Puoi leggere il racconto e proseguire.';}
function finale(){state.finished=true;markDone();save();const body=`<p>«Grazie, Mate! Hai liberato me e il mio segreto. Guarda un quadrato di lato 1: la sua diagonale misura <b>√2</b>, perché 1² + 1² = 2.</p><p>√2 non è il rapporto fra due numeri interi: è un <b>numero irrazionale</b>. La sua scrittura decimale continua senza terminare e senza ripetersi periodicamente. <b>1,41 è solo un’approssimazione. Quindi ci sono altri numeri oltre ai numeri interi e al rapporto tra di essi!</b>»</p><div class="reward">√2</div>${CONFIG.finaleAudio?`<div class="ippaso-audio"><label for="ippasoAudio">Ascolta il messaggio di Ippaso</label><audio id="ippasoAudio" controls preload="none" src="${esc(CONFIG.finaleAudio)}"></audio><p id="ippasoAudioStatus" class="small" role="status"></p></div>`:''}`;modal('Il segreto della radice di due',body,[...(CONFIG.finaleVideo?[['Guarda il video di Ippaso',()=>video(CONFIG.finaleVideo,'Ippaso e il segreto',finale),'primary']]:[]),['Scarica il tuo attestato',certificate,'primary'],['Il mio viaggio',journal],['Torna a esplorare',close]],'MISSIONE COMPIUTA · IPPASO È LIBERO');const audio=$('#ippasoAudio');if(audio)audio.onerror=()=>{$('#ippasoAudioStatus').textContent='La registrazione non è ancora disponibile. Puoi leggere il messaggio qui sopra.';};}
function journal(){const notes=['DO','RE','MI','FA','SOL','LA','SI'];modal('Il mio viaggio',`<p class="small">I tuoi indizi rimangono qui. I progressi sono salvati soltanto in questo browser.</p><div class="journal-list">${state.rewards.length?state.rewards.map(r=>`<div class="journal-row"><b>${esc(r)}</b>${r==='Stella pitagorica'?' · Simbolo della comunità':r==='Pentagramma musicale'?' · Il dono della musica':''}</div>`).join(''):'<p>Il tuo viaggio comincia adesso.</p>'}</div><h3>Le note ritrovate</h3><div class="notes">${notes.map((n,i)=>`<span class="note ${i<state.notes?'got':''}">${i<state.notes?n:'—'}</span>`).join('')}</div>${state.finished?'<p class="math">RADICE · DI · DUE → √2</p><p>Ippaso è libero. Hai completato l’avventura!</p>':''}`,[...(state.finished?[['Il mio attestato',certificate,'primary']]:[]),['Continua a esplorare',close]]);}
function map(){const chapters=[{n:1,title:'Il segreto dei pitagorici',desc:'Tre parole e una stella',start:1,unlock:1},{n:2,title:'L’armonia dei numeri',desc:'Sette note, un nuovo dono',start:6,unlock:6},{n:3,title:'Il segreto della diagonale',desc:'Raggiungi e libera Ippaso',start:8,unlock:8}];modal('Le porte di Crotone','<p>Ogni capitolo si apre completando il precedente.</p><div class="map-grid" id="chapterCards"></div>',[['Riprendi la tappa attuale',close,'primary'],['Rivedi il benvenuto',intro]]);for(const c of chapters){const b=document.createElement('button'),locked=state.max<c.unlock;b.className='map-card';b.disabled=locked;b.innerHTML=`<span class="num">${locked?'⌑':'0'+c.n}</span><strong>${c.title}</strong><small>${locked?'Ancora da sbloccare':c.desc}</small>`;b.onclick=()=>{if(c.start>state.max){intro();return;}go(c.start);};$('#chapterCards').appendChild(b);}}
function menu(){modal('Il tuo viaggio a Crotone','<p class="small">Un’avventura di Claudia Bartoli · Mate e Matica</p>',[['Come si gioca',help,'primary'],['Privacy',privacy],['Licenza d’uso',()=>window.open('LICENSE.txt','_blank','noopener')],['Storia e fonti',sources],['Ricomincia da capo',restart],['Chiudi',close]]);}
function help(){modal('Guardati intorno',`<p><b>Trascina</b> con il mouse o con un dito per ruotare l’ambiente. Usa <b>＋ e −</b>, la rotellina o due dita per ingrandire.</p><p>Gli oggetti nascondono aree cliccabili trasparenti. Se ti serve una mano, premi <b>Mostra curiosità</b>: appariranno i punti da esplorare. Le frecce della tastiera ruotano la visuale.</p><p>Le missioni si aprono toccando tavolette, pergamene e oggetti. Esplora tutte le risorse per sbloccare il passo successivo. Una risposta sbagliata ti riporta indietro, ma conservi i premi.</p><p class="small">Per giocare non occorrono nome, account o connessione a servizi esterni. I file devono essere già caricati nel browser. Il pulsante ♪ controlla i suoni degli esercizi; gli eventuali video hanno i propri controlli.</p>`,[['Ho capito',close,'primary']]);}
function privacy(){modal('Privacy',`<p>Questa applicazione non richiede account, nome o altri dati personali e non contiene pubblicità, strumenti di analisi o tracciamento inseriti nel codice.</p><p>Il nome facoltativo sull’attestato viene elaborato solo nel browser, non viene trasmesso né salvato nei progressi.</p><p>Il browser memorizza localmente tappe, risorse esplorate, ricompense e preferenza audio, esclusivamente per permetterti di riprendere il gioco. Questi progressi non sono inviati all’autrice. Puoi eliminarli con «Ricomincia da capo» oppure cancellando i dati del sito nel browser.</p><p>Immagini, codice e gli eventuali video locali sono caricati dallo stesso sito. Il servizio che ospita l’app può trattare dati tecnici di connessione secondo la propria informativa. Il codice non carica font, video incorporati o altri servizi esterni automaticamente.</p><p>I collegamenti alle fonti aprono siti esterni solo se li scegli. Per informazioni: <a href="mailto:${CONFIG.email}">${CONFIG.email}</a>.</p>`,[['Chiudi',close,'primary']]);}
function sources(){modal('Una storia per imparare',`<p>L’avventura è una rielaborazione creativa di fonti storiche a fini didattici, con licenza poetica nella narrazione e nella rappresentazione degli ambienti e dei personaggi.</p><ul>${SOURCES.map(([t,u])=>`<li><a href="${u}" target="_blank" rel="noopener noreferrer">${t}</a></li>`).join('')}</ul>`,[['Chiudi',close,'primary']]);}

function restart(){modal('Ricominciare il viaggio?','<p>Questa scelta cancella i progressi salvati su questo browser e ti riporta all’inizio.</p>',[['Conserva il mio viaggio',close,'primary'],['Cancella e ricomincia',()=>{state=initial();save();go(0);}]]);}
function setMissionHidden(hidden){$('#missionPanel').hidden=hidden;$('#showMission').hidden=!hidden;$('#hideMission').setAttribute('aria-expanded',String(!hidden));$('#showMission').setAttribute('aria-expanded',String(!hidden));}
$('#hideMission').onclick=()=>{setMissionHidden(true);$('#showMission').focus();};$('#showMission').onclick=()=>{setMissionHidden(false);$('#hideMission').focus();};
$('#continue').onclick=next;$('#mapBtn').onclick=map;$('#journalBtn').onclick=journal;$('#menuBtn').onclick=menu;$('#reveal').onclick=()=>{const active=document.body.classList.toggle('show-spots');$('#reveal').setAttribute('aria-pressed',String(active));$('#reveal').textContent=active?'✧ Nascondi curiosità':'✧ Mostra curiosità';};$('#zoomIn').onclick=()=>viewer?.zoom(-9);$('#zoomOut').onclick=()=>viewer?.zoom(9);$('#sound').onclick=()=>{state.sound=!state.sound;save();refresh();if(state.sound)beep();};$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('Usa la modalità a schermo intero del browser.');}catch(e){toast('Lo schermo intero non è disponibile in questo browser.');}};
try{viewer=new PanoramaViewer('panorama',project);go(state.current);}catch(e){$('#loading').hidden=true;modal('Serve la visualizzazione 3D','<p>Il browser non ha attivato WebGL. Prova ad aprire il sito in un browser aggiornato con accelerazione grafica attiva.</p>');}
