/* Contenuti modificabili. u e v sono coordinate normalizzate sul panorama originale.
   Le schede storiche distinguono tradizione, matematica e invenzione narrativa. */
const CONFIG={introVideo:'intro.mp4',finaleVideo:'',email:'claudiabartoli77@libero.it',storageKey:'mate-crotone-v1'};
const SOURCES=[['Pitagora e le tradizioni sulla comunità','https://plato.stanford.edu/entries/pythagoras/'],['Pitagorismo e tradizioni su Ippaso','https://plato.stanford.edu/entries/pythagoreanism/']];
const RULES=[
 ['Le fave','La tradizione attribuisce ai pitagorici il divieto di mangiare fave. Le spiegazioni proposte nel tempo sono diverse: non conosciamo con certezza il significato originario del precetto. È una curiosità storica, non una regola alimentare da seguire oggi.',.075,.60],
 ['Il cibo caduto','Fra i precetti tramandati compare il divieto di raccogliere il cibo caduto. La comunità aveva prescrizioni rituali che regolavano anche i gesti quotidiani. Il loro significato non è sempre chiaro.',.255,.735],
 ['Il gallo bianco','Secondo la tradizione, tra i membri della setta vi era il divieto di <b>toccare un gallo bianco</b>, considerato un animale sacro e legato alla luce.',.39,.61],
 ['Il pane','Un altro precetto tramandato invitava a non spezzare il pane. Le regole della comunità potevano avere un significato rituale o simbolico: non sono teoremi matematici.',.605,.55],
 ['Il calzare destro','Si racconta che si dovesse indossare prima il calzare destro. Anche un gesto comune poteva far parte della disciplina della comunità.',.856,.61],
 ['La strada affollata','Un precetto invitava a evitare le strade molto frequentate. Le interpretazioni di queste massime sono cambiate nel tempo: distinguiamo il testo tramandato dalle spiegazioni successive.',.934,.414]
];
const MUSIC=[
 ['La leggenda della fucina','Secondo un racconto tramandato molto tempo dopo Pitagora, il suono dei martelli attirò la sua attenzione. È una leggenda suggestiva: i rapporti fra i pesi dei martelli non spiegano direttamente le consonanze. Per fare esperimenti affidabili passiamo alle corde!',.17,.65,'forge'],
 ['Il monocordo','Il monocordo ha una corda tesa e un ponticello che permette di cambiare la lunghezza della parte che vibra. Nei nostri confronti manteniamo uguali materiale, spessore e tensione: accorciando la parte vibrante, il suono diventa più acuto.',.72,.665,'mono'],
 ['L’ottava','Se la parte vibrante della corda passa dalla lunghezza L a L/2, la frequenza raddoppia. Ascoltiamo la stessa nota un’ottava più in alto: per esempio DO e DO acuto. Rapporto fra frequenze: 2 : 1.',.81,.71,'octave'],
 ['La quinta','Se la lunghezza vibrante diventa 2/3 di quella iniziale, la frequenza diventa 3/2: otteniamo una quinta. Nel nostro esempio ascolti DO e SOL.',.875,.63,'fifth'],
 ['La quarta','Se la lunghezza vibrante diventa 3/4 di quella iniziale, la frequenza diventa 4/3: otteniamo una quarta. Nel nostro esempio ascolti DO e FA.',.93,.75,'fourth'],
 ['Numeri e armonia','Ottava, quinta e quarta mostrano rapporti semplici fra numeri interi. Attenzione: il rapporto fra le lunghezze è inverso a quello fra le frequenze. Le sette note DO, RE, MI, FA, SOL, LA, SI e il pentagramma musicale sono strumenti di lettura moderni del nostro gioco, non la notazione della Crotone antica.',.465,.49,'ratios']
];
const GEOMETRY=[
 ['La corda e l’angolo retto','Una corda chiusa divisa in 12 intervalli uguali può essere tesa in tre tratti da 3, 4 e 5 intervalli. Il triangolo è rettangolo perché 3² + 4² = 5². Nel nostro laboratorio gli agrimensori mostrano questa costruzione: la scena è una ricostruzione didattica, non la documentazione di un episodio preciso.',.31,.72,'rope'],
 ['Terne primitive','Tre interi positivi a, b, c formano una terna pitagorica se a² + b² = c², con c maggiore degli altri due. Una terna è primitiva se il massimo comune divisore dei tre numeri è 1. Esempi: (3, 4, 5), (5, 12, 13), (8, 15, 17).',.448,.722,'triples'],
 ['Dalle primitive alle altre terne','Moltiplica tutti e tre i termini per lo stesso intero positivo. Da (3, 4, 5), moltiplicando per 2, ottieni (6, 8, 10). La relazione resta valida: 36 + 64 = 100. Per ottenere una terna non primitiva scegli un moltiplicatore maggiore di 1.',.50,.755,'multiple'],
 ['Cateti e ipotenusa','Un triangolo rettangolo ha un angolo di 90°. I due lati che formano questo angolo si chiamano cateti. Il lato opposto all’angolo retto è l’ipotenusa: è il lato più lungo.',.785,.45,'triangle'],
 ['Il teorema di Pitagora','In un triangolo rettangolo, l’area del quadrato costruito sull’ipotenusa è uguale alla somma delle aree dei quadrati costruiti sui cateti. Se a e b sono i cateti e c è l’ipotenusa: a² + b² = c². Quindi c = √(a² + b²); per un cateto: a = √(c² − b²).',.79,.59,'theorem']
];
const TRIPLES=[[3,4,5],[5,12,13],[8,15,17],[7,24,25],[9,12,15],[6,8,10],[12,16,20]];
const SCENES=[
 {id:'arrival',title:'Un segreto scomparso',chapter:0,image:'01-crotone.webp',mission:'Pitagora ti aspetta. Cerca il maestro e scopri che cosa è accaduto a Ippaso.',start:.50,spots:[{id:'welcome',u:.5,v:.54,w:100,h:220,label:'Parla con Pitagora',action:'intro'},{id:'harbor',u:.20,v:.52,w:130,h:80,label:'Il porto',text:'Una nave si prepara a lasciare Crotone. Nella nostra storia qualcuno vuole imbarcare l’ampolla che imprigiona Ippaso. Hai una missione: trovarlo e liberarlo insieme al suo segreto.'}]},
 {id:'rules',title:'La casa dei pitagorici',chapter:1,image:'02-regole.webp',mission:'Esplora i sei oggetti e scopri i precetti tramandati dalla comunità.',start:.5,explore:'rules'},
 {id:'pebbles',title:'Il cortile dei sassolini',chapter:1,image:'03-sassolini.webp',mission:'Cerca la tavoletta sul tavolo: i numeri possono prendere forma.',start:.5,task:'pebbles',reward:'TUTTO',back:1,spots:[{id:'task',u:.63,v:.705,w:165,h:95,label:'La tavoletta dei sassolini',action:'task'},{id:'figures',u:.25,v:.50,w:90,h:150,label:'Numeri figurati',text:'Disponendo sassolini in righe puoi costruire triangoli e quadrati. Con righe da 1, 2 e 3 sassolini ottieni un triangolo formato da 6 sassolini: 1 + 2 + 3 = 6.'}]},
 {id:'pairs',title:'La stanza delle coppie',chapter:1,image:'04-pari.webp',mission:'Le pedine nei cestini custodiscono il secondo frammento del motto.',start:.5,task:'pairs',reward:'È',back:2,spots:[{id:'task',u:.425,v:.67,w:170,h:105,label:'I cestini delle pedine',action:'task'},{id:'even',u:.61,v:.67,w:100,h:70,label:'Una regola da scoprire',text:'Un numero naturale è pari se puoi raggruppare tutti i suoi oggetti a coppie senza avanzi. Se rimane un oggetto solo, il numero è dispari.'}]},
 {id:'sequence',title:'La stanza delle successioni',chapter:1,image:'05-sequenze.webp',mission:'Trova la tavoletta e scopri quale numero continua la sequenza.',start:.5,task:'sequence',reward:'NUMERO',back:3,spots:[{id:'task',u:.49,v:.661,w:140,h:80,label:'La tavoletta della sequenza',action:'task'},
 {id:'successione',u:.433,v:.637,w:90,h:75,label:'Che cos’è una successione?',text:'Una <b>successione</b> è una lista ordinata di elementi, chiamati <b>termini</b>. In una successione numerica ogni termine è un numero e occupa una posizione: primo, secondo, terzo… Per esempio: <b>2, 4, 6, 8, 10…</b>'},
 {id:'regola-sequenza',u:.556,v:.64,w:90,h:75,label:'Come continua la successione?',text:'Per continuare una successione devi conoscere la sua <b>regola</b>. Se aggiungi sempre 3, da 2 ottieni <b>2, 5, 8, 11, 14…</b> Questa è una successione aritmetica: la differenza tra termini consecutivi è costante. Nella prova della tavoletta ti viene detto che si aggiunge sempre la stessa quantità: confronta due termini vicini per scoprirla. Un elenco finito, da solo, può ammettere più regole.'},
 {id:'vita-vegetariana',u:.075,v:.595,w:90,h:110,label:'Vegetarianismo e metempsicosi',text:'<b>Vegetarianismo assoluto, secondo alcune tradizioni.</b> L’astensione dalla carne era collegata alla credenza nella <b>metempsicosi</b>: l’anima può reincarnarsi in altri corpi, umani o animali. Le testimonianze antiche non concordano sull’applicazione di questa regola a tutti i pitagorici.'},
 {id:'beni',u:.928,v:.52,w:100,h:100,label:'Comunione dei beni',text:'<b>Comunione dei beni.</b> La tradizione descrive una comunità in cui i beni materiali erano condivisi tra i membri. L’amicizia e la vita comune erano ideali importanti del gruppo.'},
 {id:'silenzio',u:.07,v:.30,w:80,h:100,label:'Il silenzio dei neofiti',text:'<b>Il silenzio dei neofiti.</b> Secondo racconti posteriori, i novizi dovevano osservare anni di silenzio, ascoltando gli insegnamenti del maestro. Gli <i>acusmatici</i>, cioè gli “ascoltatori”, custodivano precetti trasmessi oralmente: il termine indica una corrente della tradizione pitagorica e non semplicemente tutti i principianti.'},
 {id:'autorita',u:.93,v:.29,w:80,h:100,label:'La parola del maestro',text:'<b>L’autorità del maestro.</b> La tradizione attribuiva grande autorità alla parola di Pitagora. La formula latina <i>Ipse dixit</i>, “l’ha detto lui”, esprime il richiamo alla sua autorità. In matematica, però, oggi una dimostrazione vale per il ragionamento, non per il nome di chi la propone.'}]},
 {id:'motto',title:'La porta della comunità',chapter:1,image:'06-motto.webp',mission:'Ricomponi il motto con le tre parole conquistate. Tocca la lastra davanti alla porta.',start:.5,task:'motto',back:4,spots:[{id:'task',u:.5,v:.695,w:220,h:90,label:'La lastra del motto',action:'task'}]},
 {id:'music',title:'L’officina dell’armonia',chapter:2,image:'07-musica.webp',mission:'Esplora la fucina, il monocordo e la lira. Scopri e ascolta sei curiosità.',start:.50,explore:'music'},
 {id:'notes',title:'Le sette note ritrovate',chapter:2,image:'08-note.webp',mission:'Cerca la pergamena sotto le campane. Sette risposte corrette ricompongono la musica.',start:.5,task:'notes',back:6,spots:[{id:'task',u:.5,v:.683,w:160,h:100,label:'La pergamena delle sette note',action:'task'}]},
 {id:'geometry',title:'La riva e il tempio',chapter:3,image:'09-geometria.webp',mission:'Dalla corda degli agrimensori al triangolo di marmo: esplora tutte e cinque le risorse.',start:.30,explore:'geometry'},
 {id:'rope',title:'La corda giusta',chapter:3,image:'10-corde.webp',mission:'Trova la missione sul leggio, poi scegli una delle tre corde.',start:.5,task:'rope',reward:'RADICE',back:8,spots:[{id:'task',u:.5,v:.51,w:145,h:110,label:'Il leggio dell’agrimensore',action:'task'}]},
 {id:'triangle',title:'Il triangolo del tempio',chapter:3,image:'11-triangolo.webp',mission:'Tocca il triangolo di marmo: distingui cateti, ipotenusa e angolo retto.',start:.5,task:'triangle',reward:'DI',back:9,spots:[{id:'task',u:.5,v:.56,w:230,h:230,label:'Il triangolo di marmo',action:'task'}]},
 {id:'hypotenuse',title:'Il passaggio sul canale',chapter:3,image:'12-canale.webp',mission:'Trova la tavoletta del costruttore e calcola la lunghezza del passaggio diagonale.',start:.5,task:'hypotenuse',back:10,spots:[{id:'task',u:.33,v:.70,w:155,h:100,label:'La tavoletta del costruttore',action:'task'}]},
 {id:'square',title:'La piazza delle due strade',chapter:3,image:'13-piazza.webp',mission:'Leggi il cartello, poi scegli il percorso più breve e calcola quanto risparmi.',start:.5,task:'square',back:11,spots:[{id:'sign',u:.375,v:.648,w:115,h:75,label:'Il cartello delle distanze',action:'sign'},{id:'task',u:.53,v:.60,w:200,h:160,label:'Scegli il percorso',action:'task'}]},
 {id:'ladder',title:'L’ampolla sul muro',chapter:3,image:'14-muro.webp',mission:'Ippaso è nell’ampolla! Scopri le misure e scegli il solco in cui posare la scala.',start:.5,task:'ladder',back:12,spots:[{id:'task',u:.26,v:.665,w:185,h:115,label:'Le misure del muro e della scala',action:'task'},{id:'bottle',u:.535,v:.264,w:75,h:95,label:'L’ampolla di Ippaso',text:'Dentro il vetro brilla una piccola figura. È Ippaso! L’ampolla è destinata alla nave del porto. La scala deve arrivare esattamente alla mensola che la sostiene per poter prendere l’ampolla e liberare Ippaso.'}]},
 {id:'finale',title:'Il segreto liberato',chapter:3,image:'15-spiaggia.webp',mission:'Ippaso è libero. Incontralo sulla spiaggia e scopri il segreto della radice di due.',start:.5,spots:[{id:'finale',u:.49,v:.65,w:230,h:170,label:'Ascolta Ippaso',action:'finale'}]}
];
