/* Panorama sferico locale; Three.js MIT. Coordinate hotspot: u,v in [0,1] nell'immagine. */
class PanoramaViewer{
 constructor(id,onFrame){this.el=document.getElementById(id);this.lon=180;this.lat=0;this.fov=72;this.token=0;this.onFrame=onFrame;this.points=new Map();this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(72,1,.1,100);this.renderer=new THREE.WebGLRenderer({antialias:false,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.el.appendChild(this.renderer.domElement);const g=new THREE.SphereGeometry(20,64,40);g.scale(-1,1,1);this.mesh=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:0x263f49}));this.scene.add(this.mesh);new ResizeObserver(()=>this.resize()).observe(this.el);this.resize();this.bind();this.animate();}
 resize(){const w=this.el.clientWidth,h=this.el.clientHeight;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 bind(){this.el.addEventListener('pointerdown',e=>{this.el.setPointerCapture(e.pointerId);this.points.set(e.pointerId,{x:e.clientX,y:e.clientY});this.el.classList.add('dragging');});this.el.addEventListener('pointermove',e=>{if(!this.points.has(e.pointerId))return;const old=this.points.get(e.pointerId);if(this.points.size===1){this.lon-=(e.clientX-old.x)*.13*this.fov/72;this.lat+=(e.clientY-old.y)*.13*this.fov/72;this.lat=Math.max(-60,Math.min(60,this.lat));}else{const other=[...this.points.entries()].find(([k])=>k!==e.pointerId)[1];const a=Math.hypot(old.x-other.x,old.y-other.y),b=Math.hypot(e.clientX-other.x,e.clientY-other.y);if(b>0)this.zoom(this.fov*a/b-this.fov);}this.points.set(e.pointerId,{x:e.clientX,y:e.clientY});});for(const ev of ['pointerup','pointercancel'])this.el.addEventListener(ev,e=>{this.points.delete(e.pointerId);if(!this.points.size)this.el.classList.remove('dragging');});this.el.addEventListener('wheel',e=>{e.preventDefault();this.zoom(e.deltaY*.035)},{passive:false});}
 zoom(d){this.fov=Math.max(32,Math.min(this.maxFov||90,this.fov+d));this.camera.fov=this.fov;this.camera.updateProjectionMatrix();}
 look(u,v=.5){this.lon=u*360;this.lat=90-v*180;}
 setImage(url,u=.5,v=.5){this.look(u,v);this.zoom(72-this.fov);const token=++this.token;return new Promise((resolve,reject)=>{new THREE.TextureLoader().load(url,t=>{if(token!==this.token){t.dispose();resolve(false);return;}t.encoding=THREE.sRGBEncoding;t.minFilter=THREE.LinearFilter;t.generateMipmaps=false;const old=this.mesh.material;this.mesh.material=new THREE.MeshBasicMaterial({map:t});if(old.map)old.map.dispose();old.dispose();resolve(true);},undefined,reject);});}
 point(u,v){const p=v*Math.PI,t=u*Math.PI*2;return new THREE.Vector3(Math.sin(p)*Math.cos(t),Math.cos(p),Math.sin(p)*Math.sin(t));}
 project(u,v){const p=this.point(u,v);const dir=new THREE.Vector3();this.camera.getWorldDirection(dir);if(p.dot(dir)<.1)return null;p.project(this.camera);if(Math.abs(p.x)>1.3||Math.abs(p.y)>1.3)return null;return {x:(p.x+1)*this.el.clientWidth/2,y:(1-p.y)*this.el.clientHeight/2};}
 animate(){this.raf=requestAnimationFrame(()=>this.animate());this.camera.lookAt(this.point(this.lon/360,(90-this.lat)/180));this.camera.updateMatrixWorld();this.renderer.render(this.scene,this.camera);this.onFrame?.();}
}
